FROM node:14.17.3-alpine3.14
WORKDIR /app/server
RUN apk add bash
#instead of . you can do /app/client, but because the working directory is /app/clinet we will use . that means the working directory
COPY package-lock.json .
COPY package.json .
# RUN if [ "$NODE_ENV" = "DEV" ]; \
#     then npm install; \
#     else npm install --only=production; \
#     fi
RUN npm install
COPY . .
CMD [ "npm", "start" ]