version: '3'
services:
  react-app:
    build: 
      context: $PWD/client/
      dockerfile: $PWD/Docker/DockerFiles/Dockerfile.react
    depends_on:
      - nginx
      - mongo
      - express-app
    environment:
      - PORT=3000
    command: npm start
  express-app:
    #the path where the DockerFile
    build: 
      context: $PWD/Server/
      dockerfile: $PWD/Docker/DockerFiles/Dockerfile.express
    environment:
      - PORT=3001
  nginx:
    image: nginx:alpine
    volumes:
      - $PWD/nginx/default.conf:/etc/nginx/conf.d/default.conf
  mongo:
    image: mongo:4.4.6-bionic
    volumes:
      - mongodb_volume:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mohammed_bouassida
      - MONGO_INITDB_ROOT_PASSWORD=Tri_201
volumes:
  mongodb_volume: