export const ADD_ERROR = "ADD_ERROR"
export const REMOVE_ERROR = "REMOVE_ERROR"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const LOAD_MESSAGES = "LOAD_MESSAGES"
export const REMOVE_MESSAGE = "REMOVE_MESSAGE"
export const ADD_MESSAGE = "ADD_MESSAGE"
export const MODIFY_MESSAGE = "MODIFY_MESSAGE"
export const SHOW = "SHOW"
export const ADD_COMMENT = "ADD_COMMENT"
export const MODIFY_COMMENT = "MODIFY_COMMENT"
export const DELETE_COMMENT = "DELETE_COMMENT"
export const TOGGLE_LIKE = "ADD_LIKE"






